name: Set up Node.js for NPM
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  if: steps.check.outputs.changed == 'true'
  uses: actions/setup-node@v1.2.0
  with:
    registry-url: 'https://registry.npmjs.org' # This is just the default registry URL

name: Install dependencies
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  if: steps.check.outputs.changed == 'true'
  run: npm build-lib

name: Publish the package to NPM
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  if: steps.check.outputs.changed == 'true'
  run: npm publish
  env:
    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # NPM will automatically authenticate with this